name: Scrape DOGE data
on:
  workflow_dispatch:
  

  
permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:

    - name: check-out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install R packages
      run: |
        R -e "install.packages(c('plyr', 'dplyr', 'rvest', 'janitor', 'jsonlite'))"
    - name: R Scraper
      run: Rscript doge_R_scraper.R
        
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install reqs
      run: pip install -r requirements.txt
    - name: install lxml
      run: pip install lxml

    - name: Python Processor
      run: python doge-scrape.py

    - name: Commit files
      run: |
        git config --local user.name github-actions
        git config --local user.email "actions@github.com"
        git add data/*
        git commit -am "Data Updated $(date)"
        git push origin master
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
    
