name: Scrape DOGE data
on:
  workflow_dispatch:

  
permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:

    # Step 1: check-out repo
    - name: check-out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Step 2: install python and required packages
    - name: install reqs
      run: pip install -r requirements.txt

    # Step 3: run DOGE scraper
    - name: scrape DOGE
      run: python doge-scrape.py

    - name: Save datestamp
      run: date > ./data/latest-scrape.txt
    - name: Commit and push
      run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add ./data/
          git commit -m "Date Updated" && git push || true
    
