name: Scrape DOGE data
on:
  workflow_dispatch:
  

  
permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:

    - name: check-out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install reqs
      run: pip install -r requirements.txt
    - name: install lxml
      run: pip install lxml

    - name: scrape DOGE
      run: python doge-scrape.py

    - name: commit and push
      run: |
        git config remote.origin.url https://github.com/emvestigates/DOGE_PULLS.git
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git add data/*.csv
        git commit -m "Data Updated" || exit 0
        git pull
        git push
    
